web:
  build: .
  volumes:
    - .:/myapp
  ports:
    - "80:3000"
  links:
     - db:sql_srv
    depends_on:
      - db
db:
  image: library/mysql:5.6.22
  ports:
    - "3306:3306"
  environment:
      MYSQL_USER: root
